[package]
name = "api-test"
version = "0.1.0"
edition = "2021"

[dependencies]
snarkvm = { git = "ssh://git@github.com/AleoNet/snarkVM.git", branch = "mainnet" }
anyhow = "1"
reqwest = "0.11"
serde_json = "1"

tokio = {version = "1", features = ["full"]}
